# This is a basic workflow to help you get started with Actions

name: 爪巴

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
  - cron: "0 0 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Clear Previous
        run: |
          del *.jar
          del *.json
      - name: Run Application
        run: .\Mirror.exe
      - name: Commit files
        run: |
         git config --local user.email "1903518149@qq.com"
         git config --local user.name "xingxing2008"
         git add -- *
         git commit -m "update | Github Actions | "
         
      - name: Push changes
        uses:  ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          branch: main
      
